# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: message.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rmessage.proto\x12\x03\x61pi\" \n\x0b\x41uthRequest\x12\x11\n\tuser_name\x18\x01 \x01(\t\"%\n\x0c\x41uthResponse\x12\x15\n\ris_authorized\x18\x01 \x01(\x08\x32J\n\x0b\x41uthService\x12;\n\x12\x43heckAuthorization\x12\x10.api.AuthRequest\x1a\x11.api.AuthResponse\"\x00\x42\x07Z\x05./apib\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'message_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\005./api'
  _AUTHREQUEST._serialized_start=22
  _AUTHREQUEST._serialized_end=54
  _AUTHRESPONSE._serialized_start=56
  _AUTHRESPONSE._serialized_end=93
  _AUTHSERVICE._serialized_start=95
  _AUTHSERVICE._serialized_end=169
# @@protoc_insertion_point(module_scope)
